# Generated by Django 5.2.14 on 2026-05-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0011_extend_industry_activites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evebloodline",
            name="eve_ship_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="eve_bloodlines",
                to="eveuniverse.evetype",
            ),
        ),
    ]
