# Generated by Django 5.2.16 on 2026-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eveplanet",
            name="enabled_sections",
            field=models.BigIntegerField(
                default=0,
                help_text="Flags for loadable sections. True if instance was loaded with section.",
            ),
        ),
        migrations.AlterField(
            model_name="evesolarsystem",
            name="enabled_sections",
            field=models.BigIntegerField(
                default=0,
                help_text="Flags for loadable sections. True if instance was loaded with section.",
            ),
        ),
        migrations.AlterField(
            model_name="evetype",
            name="enabled_sections",
            field=models.BigIntegerField(
                default=0,
                help_text="Flags for loadable sections. True if instance was loaded with section.",
            ),
        ),
    ]
